# This is a basic workflow to help you get started with Actions

name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Permet d'optimiser le build Docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}  # On ajoutera plus tard ce secret dans les paramètres
         password: ${{ secrets.DOCKER_PASSWORD }}  # Le mot de passe aussi sera ajouté comme secret

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
         context: .
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/my-image:latest  # Remplace 'my-image' par le nom de ton image Docke 

 
